[package]
name = "plygnd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "threads"
path = "src/threads.rs"

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
